// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2021-04-20 15:37:59.7197473 +0200 CEST m=+0.461925001
// using data from
// https://github.com/golang/go/raw/master/CONTRIBUTORS
package project

var Contributors = []string{
	"Carl Chatfield <carlchatfield@gmail.com>",
	"Carl Henrik Lunde <chlunde@ifi.uio.no>",
	"Carl Jackson <carl@stripe.com>",
	"Carl Johnson <me@carlmjohnson.net>",
	"Carl Mastrangelo <notcarl@google.com>",
	"Carl Shapiro <cshapiro@google.com> <cshapiro@golang.org>",
	"Carlisia Campos <carlisia@grokkingtech.io>",
	"Carlo Alberto Ferraris <cafxx@strayorange.com>",
	"Carlos Alexandro Becker <caarlos0@gmail.com>",
	"Carlos Amedee <carlos@golang.org>",
	"Carlos Castillo <cookieo9@gmail.com>",
	"Carlos Cirello <uldericofilho@gmail.com>",
	"Carlos Eduardo <me@carlosedp.com>",
	"Carlos Eduardo Seo <cseo@linux.vnet.ibm.com>",
	"Carlos Iriarte <ciriarte@gmail.com>",
	"Carlos Souza <carloshrsouza@gmail.com>",
	"David Carlier <devnexen@gmail.com>",
	"Dustin Carlino <dcarlino@google.com>",
	"Juan Carlos <juanjcsr@gmail.com>",
}
